### ISSUE TITLE
Can be marked as 1.19.3 compatible, but...

### ISSUE THREAD

**Issue by sternschnaube** [samolego/FroggyFlies#2]
Thank you for this mod.
EDIT: I encounter on client side a problem, endless loop.

Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Redundant texture list for particle froggy_flies:firefly
	at Not Enough Crashes deobfuscated stack trace.(1.19.3+build.4)
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.IllegalStateException: Redundant texture list for particle froggy_flies:firefly
	at net.minecraft.client.particle.ParticleManager.loadTextureList(ParticleManager:309)
	at net.minecraft.client.particle.ParticleManager.method_45770(ParticleManager:244)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 6 more

**Comment by Scarlaid** [comment]
try using MixinTrace instead of NEC, might be more understanding because it would say what causing what
